### ISSUE TITLE
**TODO**

### ISSUE THREAD

**Issue by Brittank88** [Brittank88/FluffleBot#2]
- [ ] Finish userinfo command
- [ ] Convert bot messages to embeds
- [ ] Add League of Legends, Overwatch, Hearthstone, Rocket League, Pokémon, etc functions
    - [ ] League of Legends
    - [ ] Overwatch
    - [ ] Hearthstone
    - [ ] Rocket League
    - [ ] Pokémon
- [ ] Add search Urban Dictionary function
- [ ] Add xkcd comics function
- [ ] Add random cat pic function
- [ ] Add random snek pic function
- [ ] Interactions (Boop, Hug, Kiss, Poke, etc)
