### ISSUE TITLE
TODO - Update #1

### ISSUE THREAD

**Issue by Brittank88** [Brittank88/FluffleBot#4]
- [ ] Add userinfo command

- [ ] Convert bot messages to embeds

- [ ] Make setprefix command owner-only (for now)
